# Generated by Django 4.1.5 on 2023-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_store_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="setweekdays",
            name="end_time",
            field=models.TimeField(blank=True, default="18:00", null=True),
        ),
        migrations.AddField(
            model_name="setweekdays",
            name="start_time",
            field=models.TimeField(blank=True, default="10:00", null=True),
        ),
        migrations.DeleteModel(name="ManageTime",),
    ]
