# Generated by Django 4.1.5 on 2023-01-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_setweekdays_end_time_setweekdays_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_address",
                to="user.address",
            ),
        ),
    ]
