# Generated by Django 4.1.5 on 2023-01-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="store_category",
                to="user.category",
            ),
        ),
    ]
